export interface Boss {
  id: string;
  name: string;
  title: string;
  region: string;
  difficulty: number;
  description: string;
  lore: string;
  weaknesses: string[];
  resistances: string[];
  drops: string[];
  image: string;
  imageCompressed: string;
  bossType: "demigod" | "legend" | "optional" | "field" | "great-enemy";
  strategy?: {
    tips: string[];
    recommendedBuilds: string[];
    attackPatterns: string[];
  };
}

const PLACEHOLDER_IMAGE = "https://via.placeholder.com/1536x1024?text=Boss+Image";
const PLACEHOLDER_COMPRESSED = "https://via.placeholder.com/1536x1024?text=Boss+Image";

export const bosses: Boss[] = [
  // DEMIGODS - MAIN BOSSES
  {
    id: "malenia",
    name: "Malenia",
    title: "Blade of Miquella",
    region: "Elphael, Brace of the Haligtree",
    difficulty: 10,
    description: "Uma guerreira graceful com armadura dourada e uma lâmina curva. Malenia é conhecida por sua velocidade de ataque incomparável e capacidade de curar-se durante o combate. Ela inflige Scarlet Rot na fase 2.",
    lore: "Malenia é a filha de Radagon e Marika, a Rainha Eterna. Ela é a Lâmina de Miquella, dedicada a proteger seu irmão. Apesar de ser cega, sua habilidade em combate é lendária, tendo derrotado o Starscourge Radahn em uma batalha épica durante o Shattering.",
    weaknesses: ["Congelamento", "Sangramento"],
    resistances: ["Sagrado"],
    drops: ["480,000 Runes", "Malenia's Great Rune", "Remembrance of the Rot Goddess"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/malenia_blade_of_miquella-C28dtRguZKXDGtk2KHiGJ4.png",
    imageCompressed: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/malenia_blade_of_miquella-PQ5e96ZA8KtWEm5DhmzAXN.webp",
    bossType: "demigod",
    strategy: {
      tips: ["Use Bloodhound's Step para esquivar seus ataques rápidos", "Foque em dano de Hemorrhage para quebrar sua postura", "Mantenha distância e ataque após seus combos", "Na fase 2, use escudo para bloquear Scarlet Rot", "Summon Tiche ou Mimic Tear para ajudar no combate"],
      recommendedBuilds: ["Dexterity Build com Bloodhound's Step", "Hemorrhage Build com Dual Curved Swords", "Magic Build com Comet Azure", "Mimic Tear Summon para copiar seu build"],
      attackPatterns: ["Fase 1: Ataques rápidos em sequência, esquive para trás", "Fase 2: Adiciona Scarlet Rot, crie distância após cada combo", "Waterfowl Dance: Seu ataque mais perigoso, use Bloodhound's Step ou rolar para trás"],
    },
  },
  {
    id: "radahn",
    name: "Radahn",
    title: "Starscourge",
    region: "Redmane Castle, Caelid",
    difficulty: 9,
    description: "Um demigod massivo com cabelo vermelho e armadura escarlate, montado em um pequeno cavalo. Radahn é um guerreiro lendário que controla a gravidade. Extremamente fraco a Scarlet Rot.",
    lore: "Radahn é o Starscourge, um dos demigods mais poderosos. Ele conquistou as Terras Intermediárias através de sua força bruta e domínio da magia da gravidade. Sua batalha contra Malenia foi épica, deixando ambos gravemente feridos. Ele foi corrompido pela Scarlet Rot.",
    weaknesses: ["Podridão Escarlate", "Sangramento"],
    resistances: ["Magia"],
    drops: ["70,000 Runes", "Radahn's Great Rune", "Remembrance of the Starscourge"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/starscourge_radahn-dpDzxbgGwxsHvw9btqKAza.png",
    imageCompressed: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/starscourge_radahn-nGLA6XWWadwow3YKLAQKvL.webp",
    bossType: "demigod",
    strategy: {
      tips: ["Evite ficar embaixo dele para não levar dano de queda", "Use Spirit Summons para distrair enquanto ataca", "Foque em ataques rápidos após seus combos", "Scarlet Rot é extremamente eficaz contra ele", "Mantenha distância de seus ataques de gravidade"],
      recommendedBuilds: ["Scarlet Rot Build com Rotten Breath", "Melee Build com armas de alcance médio", "Magic Build com sorceries de longa distância", "Poison Build para dano contínuo"],
      attackPatterns: ["Ataques de espada lentos mas poderosos", "Gravidade: Puxa você em sua direção, esquive para o lado", "Meteor: Cria meteoros que caem, mantenha movimento", "Fase 2: Ataques mais rápidos e mais agressivos"],
    },
  },
  {
    id: "morgott",
    name: "Morgott",
    title: "The Omen King",
    region: "Leyndell",
    difficulty: 8,
    description: "Um demigod regal com uma coroa e armadura dourada ornamentada. Morgott é o protetor do Elden Ring e o último guardião antes do confronto final.",
    lore: "Morgott é o filho de Marika e Radagon. Ele é o Rei Presságio, um protetor do Elden Ring que se recusa a deixar qualquer um desafiar a ordem estabelecida. Apesar de sua natureza de presságio, ele permanece leal à vontade de Marika.",
    weaknesses: ["Sangramento", "Congelamento"],
    resistances: ["Sagrado"],
    drops: ["120,000 Runes", "Morgott's Great Rune", "Remembrance of the Omen King"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/morgott_omen_king-J8YechDMm4zXvtFo7k92wA.png",
    imageCompressed: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/morgott_omen_king-JjdGVfyhrByJT9VhcYsuBd.webp",
    bossType: "demigod",
    strategy: {
      tips: ["Ele é vulnerável a magia e fogo", "Use Margit's Shackle para atordoá-lo duas vezes", "Ataque após seus combos de espada", "Mantenha distância de seus ataques Holy", "Na fase 2, use escudo para bloquear Bloodflame"],
      recommendedBuilds: ["Fire Build com Flame of the Fell God", "Magic Build com Comet ou Glintstone", "Melee Build com armas de fogo", "Holy Defense Build para resistir seus ataques"],
      attackPatterns: ["Ataques de espada em sequência", "Holy Swords Rain: Cria chuva de espadas, esquive para os lados", "Spear Charge: Ataque direto, rolar para o lado", "Fase 2: Adiciona Bloodflame, mais agressivo"],
    },
  },
  {
    id: "maliketh",
    name: "Maliketh",
    title: "The Black Blade",
    region: "Farum Azula",
    difficulty: 9,
    description: "Um demigod esquelético com uma foice e robes tattered. Maliketh é o guardião da morte e wielder da Lâmina Negra.",
    lore: "Maliketh é o cão negro de Marika, o guardião da morte e da Lâmina Negra. Ele é responsável por manter a morte em seu lugar e impedir que qualquer um escape de seu destino. Sua lealdade a Marika é inabalável.",
    weaknesses: ["Sangramento"],
    resistances: ["Sagrado"],
    drops: ["70,000 Runes", "Remembrance of the Black Blade"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/maliketh_black_blade-6puSdaXnMVAQN8GJr2KuGy.png",
    imageCompressed: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/maliketh_black_blade-5MzpVqGG2nzSGFBbPC72Jz.webp",
    bossType: "demigod",
    strategy: {
      tips: ["Vulnerável a fogo e raio", "Seus ataques são rápidos, mantenha distância", "Ataque após seus combos", "Use Bloodhound's Step para esquivar ataques rápidos", "Summon Tiche para ajudar no combate"],
      recommendedBuilds: ["Fire Build com Flame of the Fell God", "Lightning Build com Golden Order Seal", "Dexterity Build com armas rápidas", "Magic Build com Comet Azure"],
      attackPatterns: ["Ataques de foice muito rápidos", "Black Blade: Ataque de morte, esquive para trás", "Destined Death: Seu ataque final, mantenha distância", "Fase 2: Adiciona mais velocidade e poder"],
    },
  },
  {
    id: "godrick",
    name: "Godrick",
    title: "The Grafted",
    region: "Limgrave",
    difficulty: 6,
    description: "Um demigod grotesco com um corpo feito de partes enxertadas. Godrick é o primeiro grande desafio, um senhor do castelo que coleciona corpos.",
    lore: "Godrick é o Enxertado, um demigod que coleciona partes de corpos para aumentar seu poder. Ele é o senhor de Stormveil Castle e um dos primeiros demigods que o jogador enfrenta. Apesar de sua aparência grotesca, ele é um guerreiro formidável.",
    weaknesses: ["Sangramento", "Fogo"],
    resistances: ["Raio"],
    drops: ["20,000 Runes", "Godrick's Great Rune", "Remembrance of the Grafted"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/godrick_grafted-Nq5em6LxEic57zegSJUBDm.png",
    imageCompressed: "https://d2xsxph8kpxj0f.cloudfront.net/310519663400781539/k3x4J5itd5UyEyi5dKqUq7/godrick_grafted-XSyh6G2R64LpF2DSXLtGyA.webp",
    bossType: "demigod",
    strategy: {
      tips: ["Primeiro boss importante, não é muito difícil", "Use Spirit Summons para ajudar no combate", "Ataque após seus combos de machado", "Mantenha distância de seus ataques de fogo", "Foco em dano de fogo para quebrar sua postura"],
      recommendedBuilds: ["Melee Build com espadas ou machados", "Fire Build para explorar fraqueza", "Magic Build com sorceries básicas", "Summon Build com Spirit Ashes"],
      attackPatterns: ["Ataques de machado lentos", "Spinning Attack: Gira seu machado, mantenha distância", "Fire Breath: Sopra fogo, esquive para o lado", "Fase 2: Adiciona dragão, mais agressivo"],
    },
  },
  {
    id: "rennala",
    name: "Rennala",
    title: "Queen of the Full Moon",
    region: "Liurnia",
    difficulty: 7,
    description: "Uma rainha mágica que protege a Academia de Raya Lucaria. Rennala é uma mãe que usa magia para defender seus filhos.",
    lore: "Rennala é a Rainha da Lua Cheia e mãe de Ranni. Ela foi a consorte de Radagon antes que ele se tornasse o marido de Marika. Agora ela reside na Academia de Raya Lucaria, protegendo seus filhos através de magia.",
    weaknesses: ["Normal"],
    resistances: ["Magia"],
    drops: ["40,000 Runes", "Remembrance of the Full Moon Queen"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "demigod",
    strategy: {
      tips: ["Vulnerável a ataques físicos", "Use armas de alcance para atacar de longe", "Mantenha distância de seus ataques mágicos", "Na fase 2, destrua os ovos antes de atacá-la", "Use Bloodhound's Step para esquivar magia"],
      recommendedBuilds: ["Melee Build com armas de alcance", "Lightning Build para explorar fraqueza", "Dexterity Build com armas rápidas", "Summon Build com Spirit Ashes"],
      attackPatterns: ["Ataques mágicos de glintstone", "Glintstone Spell: Cria projéteis de magia, esquive para os lados", "Fase 2: Cria ovos que invocam inimigos, destrua-os primeiro", "Moonblade: Ataque de lua crescente, mantenha distância"],
    },
  },
  {
    id: "rykard",
    name: "Rykard",
    title: "Lord of Blasphemy",
    region: "Mt. Gelmir",
    difficulty: 8,
    description: "Um demigod que se fundiu com uma serpente gigante. Rykard é um guerreiro que busca consumir todos os demigods.",
    lore: "Rykard é o Senhor da Blasfêmia, um demigod que se tornou uma com a Serpente Blasfema. Ele reside no Vulcão Gelmir e busca consumir todos os demigods para se tornar supremo. Sua obsessão pelo poder o levou a sacrificar sua própria humanidade.",
    weaknesses: ["Arma Serpent-Hunter"],
    resistances: ["Fogo"],
    drops: ["50,000 Runes", "Rykard's Great Rune", "Remembrance of the Blasphemous"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "demigod",
    strategy: {
      tips: ["Use a Serpent-Hunter Spear fornecida no combate", "Ataque a cabeça da serpente quando possível", "Mantenha distância de seus ataques de fogo", "A lança especial é muito eficaz contra ele", "Summon para ajudar enquanto você ataca"],
      recommendedBuilds: ["Serpent-Hunter Spear Build (fornecida)", "Fire Build para explorar resistência", "Magic Build com sorceries", "Summon Build com Spirit Ashes"],
      attackPatterns: ["Ataques de cabeça de serpente", "Fire Breath: Sopra fogo, esquive para o lado", "Serpent Slam: Bate com a cauda, mantenha distância", "Fase 2: Adiciona mais velocidade e poder"],
    },
  },
  {
    id: "mohg",
    name: "Mohg",
    title: "Lord of Blood",
    region: "Leyndell",
    difficulty: 9,
    description: "Um demigod que comanda o poder do sangue. Mohg é um guerreiro sombrio que reside em um reino subterrâneo.",
    lore: "Mohg é o Senhor do Sangue, um demigod que comanda a magia do sangue. Ele reside no Leyndell Subterrâneo e busca criar seu próprio reino. Sua obsessão pelo sangue o tornou um dos demigods mais perigosos.",
    weaknesses: ["Sangramento"],
    resistances: ["Fogo"],
    drops: ["90,000 Runes", "Mohg's Great Rune", "Remembrance of the Blood Lord"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "demigod",
    strategy: {
      tips: ["Vulnerável a raio e fogo", "Use Purifying Crystal Tear para resistir Bloodflame", "Ataque após seus combos", "Mantenha distância de seus ataques de sangue", "Summon Tiche para ajudar no combate"],
      recommendedBuilds: ["Lightning Build com Golden Order Seal", "Fire Build com Flame of the Fell God", "Dexterity Build com armas rápidas", "Magic Build com Comet Azure"],
      attackPatterns: ["Ataques de tridente rápidos", "Bloodflame: Cria chamas de sangue, esquive para trás", "Bloodboon: Ataque de área com sangue, mantenha distância", "Fase 2: Adiciona mais velocidade e poder"],
    },
  },
  {
    id: "mohg-the-omen",
    name: "Mohg",
    title: "The Omen",
    region: "Mohgwyn Palace",
    difficulty: 7,
    description: "Uma versão mais fraca do Mohg encontrada em Mohgwyn Palace. Este é um boss opcional que oferece uma alternativa ao Mohg, Lord of Blood.",
    lore: "Mohg, the Omen é uma versão anterior ou alternativa do Senhor do Sangue. Ele reside em Mohgwyn Palace e comanda a magia do sangue, mas é menos poderoso que sua versão final.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Sangue"],
    drops: ["90,000 Runes", "Mohg's Great Rune", "Remembrance of the Blood Lord"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
    strategy: {
      tips: ["Versão mais fraca que Mohg, Lord of Blood", "Vulnerável a raio e fogo", "Use Purifying Crystal Tear para resistir Bloodflame", "Ataque após seus combos", "Summon para ajudar no combate"],
      recommendedBuilds: ["Lightning Build com Golden Order Seal", "Fire Build com Flame of the Fell God", "Dexterity Build com armas rápidas", "Magic Build com Comet Azure"],
      attackPatterns: ["Ataques de tridente rápidos", "Bloodflame: Cria chamas de sangue, esquive para trás", "Bloodboon: Ataque de área com sangue, mantenha distância", "Menos agressivo que sua versão final"],
    },
  },

  // LEGEND BOSSES
  {
    id: "margit",
    name: "Margit",
    title: "The Fell Omen",
    region: "Limgrave",
    difficulty: 4,
    description: "Um chefe presságio que guarda o caminho para Stormveil Castle. Margit é um dos primeiros desafios significativos do jogo.",
    lore: "Margit é um presságio enviado para impedir que o Tarnished avance. Ele é um servo de Morgott e marca o início da jornada do jogador contra os demigods.",
    weaknesses: ["Sangramento", "Congelamento"],
    resistances: ["Sagrado"],
    drops: ["12,000 Runes", "Talisman of Margit"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
    strategy: {
      tips: ["Primeiro boss do jogo, relativamente fácil", "Use Spirit Summons para ajudar", "Ataque após seus combos", "Mantenha distância de seus ataques Holy", "Foco em dano físico"],
      recommendedBuilds: ["Melee Build com espadas", "Magic Build com sorceries básicas", "Summon Build com Spirit Ashes", "Dexterity Build com armas rápidas"],
      attackPatterns: ["Ataques de espada em sequência", "Holy Swords Rain: Cria chuva de espadas, esquive para os lados", "Spear Charge: Ataque direto, rolar para o lado", "Grab Attack: Tenta agarrá-lo, esquive para trás"],
    },
  },
  {
    id: "fire-giant",
    name: "Fire Giant",
    title: "Guardian of the Flame",
    region: "Mountaintops of the Giants",
    difficulty: 9,
    description: "Um gigante de fogo colossal que guarda a chama de Melina. Este é um dos chefes mais desafiadores do jogo.",
    lore: "O Fire Giant é um antigo guardião que protege a chama que queima o Erdtree. Sua derrota é essencial para progredir na história final do jogo.",
    weaknesses: ["Sangramento", "Congelamento"],
    resistances: ["Fogo"],
    drops: ["180,000 Runes", "Remembrance of the Fire Giant"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
    strategy: {
      tips: ["Gigante colossal, ataque as pernas para derrubá-lo", "Use Torrent para se mover rapidamente", "Mantenha distância de seus ataques de fogo", "Foco em dano de magia ou raio", "Summon para ajudar no combate"],
      recommendedBuilds: ["Magic Build com sorceries de longa distância", "Lightning Build para explorar fraqueza", "Melee Build com armas de alcance", "Summon Build com Spirit Ashes"],
      attackPatterns: ["Ataques de braço e perna", "Fire Breath: Sopra fogo em área, mantenha distância", "Stomp: Pisa no chão, use Torrent para escapar", "Fase 2: Fica mais agressivo e rápido"],
    },
  },
  {
    id: "godskin-duo",
    name: "Godskin Duo",
    title: "Twin Apostles",
    region: "Crumbling Farum Azula",
    difficulty: 9,
    description: "Dois apóstolos Godskin que lutam juntos. Este é um dos combates mais desafiadores do jogo.",
    lore: "Os Godskin Apostles são servos antigos que buscam devorar os deuses. Sua presença marca a corrupção do Farum Azula.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Sagrado"],
    drops: ["70,000 Runes", "Smithing-Stone Miner's Bell Bearing [4]", "Ash of War: Black Flame Tornado"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
    strategy: {
      tips: ["Dois apóstolos Godskin, foque em um de cada vez", "Use Bloodhound's Step para esquivar ataques", "Mantenha distância de seus ataques de fogo", "Summon para ajudar a dividir atenção", "Foco em dano de fogo ou raio"],
      recommendedBuilds: ["Fire Build com Flame of the Fell God", "Lightning Build para explorar fraqueza", "Dexterity Build com armas rápidas", "Magic Build com Comet Azure"],
      attackPatterns: ["Ataques de espada rápidos", "Fire Breath: Sopra fogo, esquive para o lado", "Grab Attack: Tenta agarrá-lo, esquive para trás", "Fase 2: Ambos ficam mais agressivos"],
    },
  },
  {
    id: "godfrey-golden-shade",
    name: "Godfrey",
    title: "First Elden Lord (Golden Shade)",
    region: "Leyndell",
    difficulty: 8,
    description: "A sombra dourada do primeiro Elden Lord. Um combate épico contra uma lenda.",
    lore: "Godfrey foi o primeiro Elden Lord, um guerreiro de poder incomparável. Sua sombra dourada testa o Tarnished em combate singular.",
    weaknesses: ["Sangramento", "Congelamento"],
    resistances: ["Sagrado"],
    drops: ["0 Runes", "Remembrance of Hoarah Loux"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
  },
  {
    id: "radagon",
    name: "Radagon",
    title: "of the Golden Order",
    region: "Leyndell",
    difficulty: 9,
    description: "O consorte de Marika e pai dos demigods. Um combate final épico.",
    lore: "Radagon é uma entidade divina que se tornou o consorte de Marika. Sua verdadeira forma é revelada no confronto final.",
    weaknesses: ["Fogo"],
    resistances: ["Sagrado"],
    drops: ["0 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
  },
  {
    id: "elden-beast",
    name: "Elden Beast",
    title: "The Final Boss",
    region: "Leyndell",
    difficulty: 10,
    description: "A manifestação viva do Elden Ring. O chefe final do jogo.",
    lore: "O Elden Beast é a encarnação do próprio Elden Ring, a lei fundamental do mundo. Derrotá-lo é o objetivo final de toda jornada.",
    weaknesses: ["Normal"],
    resistances: ["Sagrado"],
    drops: ["500,000 Runes", "Elden Ring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
  },
  {
    id: "lichdragon-fortissax",
    name: "Lichdragon Fortissax",
    title: "Death Dragon",
    region: "Deeproot Depths",
    difficulty: 9,
    description: "Um dragão antigo que comanda a morte. Um dos chefes opcionais mais desafiadores.",
    lore: "O Lichdragon Fortissax é um dragão antigo que reside nas profundezas. Sua morte é essencial para certos finais.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Sangue", "Magia"],
    drops: ["70,000 Runes", "Remembrance of the Lichdragon Fortissax"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
  },
  {
    id: "maliketh-beast-clergyman",
    name: "Beast Clergyman",
    title: "Maliketh's True Form",
    region: "Farum Azula",
    difficulty: 9,
    description: "A verdadeira forma de Maliketh. Um combate épico contra o guardião da morte.",
    lore: "O Beast Clergyman é a forma verdadeira de Maliketh, revelada após sua derrota inicial.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Raio", "Sagrado"],
    drops: ["0 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "legend",
  },

  // OPTIONAL BOSSES - DRAGONS
  {
    id: "flying-dragon-agheel",
    name: "Flying Dragon Agheel",
    title: "Sky Warden",
    region: "Limgrave",
    difficulty: 5,
    description: "Um dragão que voa sobre as terras. Um dos primeiros dragões encontrados.",
    lore: "Agheel é um dragão antigo que patrulha os céus de Limgrave.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Sagrado"],
    drops: ["5,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "glintstone-dragon-smarag",
    name: "Glintstone Dragon Smarag",
    title: "Mage Dragon",
    region: "Liurnia",
    difficulty: 7,
    description: "Um dragão que controla magia de glintstone. Um chefe desafiador para magos.",
    lore: "Smarag é um dragão antigo que domina a magia de glintstone.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Sagrado"],
    drops: ["18,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "glintstone-dragon-adula",
    name: "Glintstone Dragon Adula",
    title: "Mage Dragon",
    region: "Liurnia",
    difficulty: 7,
    description: "Um dragão poderoso que controla magia avançada de glintstone.",
    lore: "Adula é um dragão antigo e poderoso que reside em Liurnia.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Podridão"],
    drops: ["20,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "dragonlord-placidusax",
    name: "Dragonlord Placidusax",
    title: "Ancient Dragon Lord",
    region: "Crumbling Farum Azula",
    difficulty: 9,
    description: "Um dragão antigo e poderoso que reside em Farum Azula. Um dos chefes mais desafiadores.",
    lore: "Placidusax é um dragão antigo que é anterior ao Elden Ring. Sua derrota revela segredos antigos.",
    weaknesses: ["Sangramento"],
    resistances: ["Raio"],
    drops: ["280,000 Runes", "Remembrance of the Dragonlord Placidusax"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "decaying-ekzykes",
    name: "Decaying Ekzykes",
    title: "Scarlet Rot Dragon",
    region: "Caelid",
    difficulty: 7,
    description: "Um dragão corrompido pela Scarlet Rot. Um chefe perigoso e tóxico.",
    lore: "Ekzykes é um dragão que foi corrompido pela Scarlet Rot de Radahn.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Fogo", "Podridão"],
    drops: ["6,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "elder-dragon-greyoll",
    name: "Elder Dragon Greyoll",
    title: "Ancient Dragon",
    region: "Caelid",
    difficulty: 6,
    description: "Um dragão antigo e fraco. Um chefe fácil para ganhar rumas.",
    lore: "Greyoll é um dragão antigo que perdeu sua força.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Sagrado"],
    drops: ["Dragon Heart"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },

  // OPTIONAL BOSSES - DEMIGODS/LEGENDS
  {
    id: "astel-naturalborn",
    name: "Astel",
    title: "Naturalborn of the Void",
    region: "Lake of Rot",
    difficulty: 8,
    description: "Uma criatura cósmica que veio do vazio. Um chefe único e desafiador.",
    lore: "Astel é uma criatura do vazio que desce nas profundezas. Sua natureza é misteriosa e antiga.",
    weaknesses: ["Normal"],
    resistances: ["Magia"],
    drops: ["Remembrance of Astel"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "astel-stars-darkness",
    name: "Astel",
    title: "Stars of Darkness",
    region: "Consecrated Snowfield",
    difficulty: 8,
    description: "Uma variação de Astel que comanda as estrelas da escuridão.",
    lore: "Esta é uma forma alternativa de Astel encontrada em uma área diferente.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Magia"],
    drops: ["Astel Meteorite"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "mimic-tear",
    name: "Mimic Tear",
    title: "Your Shadow",
    region: "Siofra River",
    difficulty: 8,
    description: "Um espelho de si mesmo. Um chefe que copia seu equipamento e habilidades.",
    lore: "O Mimic Tear é uma cópia perfeita do jogador, criada pela magia antiga.",
    weaknesses: ["Varia conforme seu build"],
    resistances: ["Varia conforme seu build"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "fia-champions",
    name: "Fia's Champions",
    title: "The Deathbed Companions",
    region: "Deeproot Depths",
    difficulty: 7,
    description: "Três guerreiros que servem a Fia. Um combate contra múltiplos inimigos.",
    lore: "Estes são os companheiros de Fia que protegem seu repouso.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Físico"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "godskin-apostle",
    name: "Godskin Apostle",
    title: "Divine Devourer",
    region: "Siofra River",
    difficulty: 7,
    description: "Um apóstolo Godskin que busca devorar os deuses.",
    lore: "Os Godskin Apostles são antigos servos que buscam consumir a divindade.",
    weaknesses: ["Sono"],
    resistances: ["Fogo"],
    drops: ["4,000 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "godskin-noble",
    name: "Godskin Noble",
    title: "Divine Devourer",
    region: "Crumbling Farum Azula",
    difficulty: 8,
    description: "Um nobre Godskin mais poderoso. Um chefe desafiador.",
    lore: "Os Godskin Nobles são versões mais poderosas dos apóstolos.",
    weaknesses: ["Sono"],
    resistances: ["Fogo"],
    drops: ["4,000 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "commander-niall",
    name: "Commander Niall",
    title: "Warrior of the Giants",
    region: "Mountaintops of the Giants",
    difficulty: 8,
    description: "Um comandante guerreiro que lidera soldados. Um chefe desafiador.",
    lore: "Niall é um comandante experiente que protege as Mountaintops.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Físico"],
    drops: ["24,000 Runes", "Veteran Prosthesis"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },
  {
    id: "sir-gideon-ofnir",
    name: "Sir Gideon Ofnir",
    title: "The All-Knowing",
    region: "Leyndell",
    difficulty: 8,
    description: "Um cavaleiro sábio que conhece todos os feitiços. Um combate intelectual.",
    lore: "Gideon é um cavaleiro antigo que acumulou conhecimento ao longo dos séculos.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Magia"],
    drops: ["0 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "optional",
  },

  // FIELD BOSSES - CRUCIBLE KNIGHTS
  {
    id: "crucible-knight",
    name: "Crucible Knight",
    title: "Ancient Warrior",
    region: "Limgrave",
    difficulty: 5,
    description: "Um cavaleiro antigo que usa magia de crucible. Um chefe desafiador.",
    lore: "Os Crucible Knights são guerreiros antigos que dominam magia antiga.",
    weaknesses: ["Raio"],
    resistances: ["Sagrado"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },
  {
    id: "crucible-knight-siluria",
    name: "Crucible Knight Siluria",
    title: "Ancient Warrior",
    region: "Limgrave",
    difficulty: 6,
    description: "Uma variante de Crucible Knight com habilidades diferentes.",
    lore: "Siluria é um Crucible Knight especializado em combate com lâminas.",
    weaknesses: ["Raio"],
    resistances: ["Magia"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },

  // FIELD BOSSES - MISBEGOTTENS
  {
    id: "leonine-misbegotten",
    name: "Leonine Misbegotten",
    title: "Beast Warrior",
    region: "Weeping Peninsula",
    difficulty: 5,
    description: "Uma criatura leonina deformada. Um chefe agressivo.",
    lore: "Os Misbegottens são criaturas deformadas que habitam as terras.",
    weaknesses: ["Sangramento"],
    resistances: ["Raio"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },
  {
    id: "scaly-misbegotten",
    name: "Scaly Misbegotten",
    title: "Beast Warrior",
    region: "Weeping Peninsula",
    difficulty: 5,
    description: "Uma criatura escamosa deformada.",
    lore: "Uma variante dos Misbegottens com características diferentes.",
    weaknesses: ["Fogo", "Raio"],
    resistances: ["Físico"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },

  // FIELD BOSSES - TREE SPIRITS
  {
    id: "erdtree-avatar",
    name: "Erdtree Avatar",
    title: "Guardian of the Erdtree",
    region: "Múltiplas Regiões",
    difficulty: 5,
    description: "Um espírito guardião da Erdtree. Encontrado em vários locais.",
    lore: "Os Erdtree Avatars são guardiões da árvore sagrada.",
    weaknesses: ["Fogo"],
    resistances: ["Sagrado"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },
  {
    id: "ulcerated-tree-spirit",
    name: "Ulcerated Tree Spirit",
    title: "Corrupted Guardian",
    region: "Múltiplas Regiões",
    difficulty: 7,
    description: "Um espírito de árvore corrompido e perigoso.",
    lore: "Os Ulcerated Tree Spirits são versões corrompidas dos guardiões.",
    weaknesses: ["Raio", "Fogo"],
    resistances: ["Magia"],
    drops: ["4,000 Runes", "Golden Seed"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },

  // FIELD BOSSES - DRAGONS
  {
    id: "magma-wyrm",
    name: "Magma Wyrm",
    title: "Fire Serpent",
    region: "Múltiplas Regiões",
    difficulty: 6,
    description: "Uma serpente de magma que cospe fogo.",
    lore: "Os Magma Wyrms são criaturas de fogo que habitam vulcões.",
    weaknesses: ["Magia"],
    resistances: ["Fogo"],
    drops: ["5,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },
  {
    id: "flying-dragon-greyll",
    name: "Flying Dragon Greyll",
    title: "Sky Warden",
    region: "Dragonbarrow",
    difficulty: 6,
    description: "Um dragão que voa sobre Dragonbarrow.",
    lore: "Greyll é um dragão que patrulha as terras de Dragonbarrow.",
    weaknesses: ["Raio"],
    resistances: ["Fogo"],
    drops: ["5,000 Runes", "Dragon Heartstring"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "field",
  },

  // GREAT ENEMIES
  {
    id: "tree-sentinel",
    name: "Tree Sentinel",
    title: "Guardian of the Erdtree",
    region: "Limgrave",
    difficulty: 3,
    description: "Um cavaleiro dourado que guarda a entrada. Um dos primeiros desafios.",
    lore: "Os Tree Sentinels são guardiões da Erdtree espalhados por todo o mundo.",
    weaknesses: ["Raio"],
    resistances: ["Sagrado"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "draconic-tree-sentinel",
    name: "Draconic Tree Sentinel",
    title: "Dragon Guardian",
    region: "Altus Plateau",
    difficulty: 7,
    description: "Um cavaleiro dragão que guarda Leyndell.",
    lore: "O Draconic Tree Sentinel é um guardião mais poderoso que protege a capital.",
    weaknesses: ["Raio"],
    resistances: ["Fogo"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "royal-knight-loretta",
    name: "Royal Knight Loretta",
    title: "Guardian of the Carian Royalty",
    region: "Liurnia",
    difficulty: 6,
    description: "Um cavaleiro real que guarda Carian Manor.",
    lore: "Loretta é um cavaleiro leal que protege a linhagem Carian.",
    weaknesses: ["Raio"],
    resistances: ["Físico"],
    drops: ["9,000 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "red-wolf-radagon",
    name: "Red Wolf of Radagon",
    title: "Beast Guardian",
    region: "Liurnia",
    difficulty: 5,
    description: "Um lobo vermelho que guarda a Academia de Raya Lucaria.",
    lore: "O Red Wolf é um guardião mágico que protege a academia.",
    weaknesses: ["Fogo"],
    resistances: ["Magia"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "ancestor-spirit",
    name: "Ancestor Spirit",
    title: "Ancient Guardian",
    region: "Siofra River",
    difficulty: 6,
    description: "Um espírito ancestral que guarda uma área sagrada.",
    lore: "Os Ancestor Spirits são guardiões antigos de locais sagrados.",
    weaknesses: ["Raio"],
    resistances: ["Magia"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "regal-ancestor-spirit",
    name: "Regal Ancestor Spirit",
    title: "Ancient Guardian",
    region: "Siofra River",
    difficulty: 7,
    description: "Uma versão mais poderosa do Ancestor Spirit.",
    lore: "Um Ancestor Spirit mais antigo e poderoso.",
    weaknesses: ["Raio"],
    resistances: ["Magia"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "fallingstar-beast",
    name: "Fallingstar Beast",
    title: "Cosmic Horror",
    region: "Múltiplas Regiões",
    difficulty: 6,
    description: "Uma criatura cósmica que caiu das estrelas.",
    lore: "Os Fallingstar Beasts são criaturas de origem cósmica.",
    weaknesses: ["Magia"],
    resistances: ["Raio"],
    drops: ["3,000 Runes"],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "godefroy-grafted",
    name: "Godefroy the Grafted",
    title: "Demigod Clone",
    region: "Altus Plateau",
    difficulty: 6,
    description: "Uma cópia enxertada de Godrick.",
    lore: "Godefroy é um clone criado de Godrick.",
    weaknesses: ["Sangramento", "Fogo"],
    resistances: ["Raio"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
  {
    id: "elemer-briar",
    name: "Elemer of the Briar",
    title: "Thorn Knight",
    region: "Altus Plateau",
    difficulty: 6,
    description: "Um cavaleiro que comanda espinhos.",
    lore: "Elemer é um cavaleiro que domina a magia dos espinhos.",
    weaknesses: ["Fogo"],
    resistances: ["Magia"],
    drops: [],
    image: PLACEHOLDER_IMAGE,
    imageCompressed: PLACEHOLDER_COMPRESSED,
    bossType: "great-enemy",
  },
];
